[package]
name = "RusticFetch"
version = "0.1.0"
authors = ["anupsv"]
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = "0.11"
structopt = "0.3"
num_cpus = "1.13"
futures = "0.3.28"
env_logger = "0.9"
log = "0.4"